# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cash',
            new_name='balance',
        ),
    ]
