# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybudget',
            old_name='allotted',
            new_name='actual',
        ),
    ]
