# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_monthlybudget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
