# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160825_1054'),
        ('transactions', '0004_remove_transaction_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
    ]
